name: Set git branch
description: Set git branch for dependencies

inputs:
  version:
    required: true
  release-branch:
    required: true
  repo:
    required: true
  path:
    required: false
  toolchain:
    required: false
  github-token:
    required: true
  github-user:
    required: false
    default: eclipse-zenoh-bot
  deps-pattern:
    description: "Multiline list of regular expressions for dependencies (one per line)"
    required: true
  deps-git-url:
    description: "Multiline list of git URLs matching deps-pattern (one per line)"
    required: true
  deps-branch:
    description: "Multiline list of branches matching deps-pattern (one per line)"
    required: true
runs:
  using: node24
  main: ../dist/set-git-branch-main.mjs
