name: Build crates (Standalone)

inputs:
  repo:
    required: true
  version:
    required: false
  branch:
    required: false
  target:
    required: false
  artifact-patterns:
    required: true
  github-token:
    required: false

outputs:
  artifact-id:
    description: Artifact id
  artifact-name:
    description: Artifact name

runs:
  using: node20
  main: ../dist/build-crates-standalone-main.js
