name: Bump crates

inputs:
  version:
    required: true
  live-run:
    required: false
  branch:
    required: true
  repo:
    required: true
  path:
    required: false
  github-token:
    required: true
  bump-deps-pattern:
    required: false
  bump-deps-version:
    required: false
  bump-deps-branch:
    required: false

runs:
  using: node20
  main: ../dist/bump-crates-main.js
