name: Publish crates (GitHub)

inputs:
  live-run:
    required: true
  version:
    required: true
  repo:
    required: true
  branch:
    required: true
  github-token:
    required: true
  archive-patterns:
    required: false

runs:
  using: node20
  main: ../dist/publish-crates-github-main.js
