name: Publish crates (GitHub)
description: Publish artifacts to GitHub release

inputs:
  live-run:
    required: true
  version:
    required: true
  repo:
    required: true
  branch:
    required: true
  github-token:
    required: true
  archive-patterns:
    required: false

runs:
  using: node24
  main: ../dist/publish-crates-github-main.mjs
