name: Publish crates (Eclipse)

inputs:
  live-run:
    required: true
  version:
    required: true
  ssh-host:
    required: true
  ssh-host-path:
    required: true
  ssh-private-key:
    required: true
  ssh-passphrase:
    required: true

runs:
  using: node20
  main: ../dist/publish-crates-eclipse-main.js
