name: Check deps for Eclipse IPDDP compliance

on:
  workflow_call:
    inputs:
      dependencies:
        type: string
        description: dependencies can be expressed one-on-a-line using ClearlyDefined ids (e.g., maven/mavencentral/org.apache.commons/commons-csv/1.8, Maven GAVs (e.g., org.apache.commons:commons-csv:1.8, or and NPM Id (e.g., npm/npmjs/-/babel-polyfill/6.26.0).
        required: true

jobs:
  check-ipddp-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Download Eclipse IPDDP License Tool
        run: |
          wget "https://repo.eclipse.org/service/rest/v1/search/assets/download?repository=dash-maven2-releases&maven.groupId=org.eclipse.dash&maven.artifactId=org.eclipse.dash.licenses&maven.baseVersion=1.1.0&maven.extension=jar" -O org.eclipse.dash.licenses-latest.jar

      - name: Run Eclipse IPDDP License Tool
        run: |
          echo "${{ inputs.dependencies }}" >> dependencies.txt
          java -jar org.eclipse.dash.licenses-latest.jar -summary DEPENDENCIES dependencies.txt
          exit $?
