name: Recreate Cargo lockfile

on:
  schedule:
    - cron: "0 0 */14 * *" # Run fortnightly at 00:00 UTC
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The branch to sync across all dependent repositories. Defaults to the default branch of the source repository (i.e. eclipse-zenoh/zenoh)
        required: false
      toolchain:
        type: string
        description: The rust toolchain to use. Defaults to rust-toolchain.toml's channel value
        required: false

defaults:
  run:
    shell: bash

jobs:
  recreate-lockfile:
    name: Recreate Zenoh's lockfile
    runs-on: ubuntu-latest
    outputs:
      pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
    steps:
      - name: Checkout Zenoh
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: eclipse-zenoh/zenoh
          ref: ${{ inputs.branch }}

      - id: info
        name: Get HEAD info
        run: |
          echo "head-hash=$(git log -1 --format=%h)" >> $GITHUB_OUTPUT
          echo "head-date=$(git log -1 --format=%as)" >> $GITHUB_OUTPUT

      - id: toolchain
        name: Get Rust toolchain
        env:
          TOOLCHAIN_INPUT: ${{ inputs.toolchain }}
        run: |
          set -euo pipefail

          # NOTE: override to nightly toolchain so we can use cargo's -Zmin-publish-age
          # to avoid pulling in recently published dependencies possibly mitigating supply chain attacks.
          # This feature will be available in 1.100.0 scheduled for release in September 2026.
          RUST_TOOLCHAIN="nightly"
          #if [[ -n "$TOOLCHAIN_INPUT" ]]; then
          #  RUST_TOOLCHAIN="$TOOLCHAIN_INPUT"
          #else
          #  RUST_TOOLCHAIN="$(yq -r '.toolchain.channel // ""' rust-toolchain.toml)"
          #fi

          #if [[ ! "$RUST_TOOLCHAIN" =~ ^[A-Za-z0-9][A-Za-z0-9._+@-]*$ ]]; then
          #  echo "Invalid Rust toolchain" >&2
          #  exit 1
          #fi

          printf 'RUST_TOOLCHAIN=%s\n' "$RUST_TOOLCHAIN" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        # NOTE: Showing the active Rust toolchain (defined by the rust-toolchain.toml file)
        # will have the side effect of installing it; if it's not installed already.
        run: |
          rustup update "$RUST_TOOLCHAIN"
          rustup component add --toolchain "$RUST_TOOLCHAIN" clippy

      - name: Install build dependencies
        run: sudo apt-get install -y llvm-dev libclang-dev clang libacl1-dev

      - name: Recreate Cargo.lock
        run: |
          rm -f Cargo.lock
          cargo "+${RUST_TOOLCHAIN}" -Zmin-publish-age --config registry.global-min-publish-age='"14 days"' update --manifest-path Cargo.toml

      - name: Create/Update a pull request if the lockfile changed
        id: cpr
        # NOTE: If there is a pending PR, this action will simply update it with a forced push.
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "chore: recreate Cargo.lock"
          body: |
            This pull request recreates Zenoh's Cargo.lock.

            - **sha**: eclipse-zenoh/zenoh@${{ steps.info.outputs.head-hash }}
            - **date**: ${{ steps.info.outputs.head-date }}
            - **workflow**: [${{ github.run_id}}](https://github.com/eclipse-zenoh/ci/actions/runs/${{ github.run_id }})
          commit-message: "build: Recreate Cargo lockfile"
          committer: eclipse-zenoh-bot <eclipse-zenoh-bot@users.noreply.github.com>
          author: eclipse-zenoh-bot <eclipse-zenoh-bot@users.noreply.github.com>
          base: ${{ inputs.branch }}
          branch: eclipse-zenoh-bot/recreate-lockfile
          delete-branch: true
          labels: dependencies, internal
          token: ${{ secrets.BOT_TOKEN_WORKFLOW }}

      - name: Enable auto merge for the pull request
        if: contains(fromJSON('["created", "updated"]'), steps.cpr.outputs.pull-request-operation)
        run: >
          gh pr merge "${{ steps.cpr.outputs.pull-request-number }}"
          --subject "build: Recreate lockfile of ${{ steps.info.outputs.head-hash }} from ${{ steps.info.outputs.head-date }} (#${{ steps.cpr.outputs.pull-request-number }})"
          --repo "eclipse-zenoh/zenoh"
          --squash
          --auto
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN_WORKFLOW }}

      - name: Add the PR as annotation to workflow run
        if: contains(fromJSON('["created", "updated"]'), steps.cpr.outputs.pull-request-operation)
        run: >
          echo "::notice:: PR ${{ steps.cpr.outputs.pull-request-operation }}: https://github.com/eclipse-zenoh/zenoh/pull/${{ steps.cpr.outputs.pull-request-number }}"
